# Generated by Django 3.2.6 on 2021-09-09 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.DateTimeField(verbose_name='شروع مرخصی')),
                ('time2', models.DateTimeField(verbose_name='پایان مرخصی')),
                ('type', models.CharField(choices=[('h', 'ساعتی'), ('d', 'روزانه')], max_length=20, verbose_name='نوع مرخصی')),
                ('accept', models.CharField(choices=[('1', 'در دست بررسی'), ('2', 'تایید سرپرست'), ('3', 'تایید ناظر'), ('4', 'تایید نشده')], default='در دست بررسی', max_length=30, verbose_name='وضیعت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'مرحضی',
                'verbose_name_plural': 'مرحضی',
            },
        ),
    ]
