# Generated by Django 3.2.6 on 2021-09-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_alter_restmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restmodel',
            name='accept',
            field=models.CharField(choices=[('در دست بررسی', 'در دست بررسی'), ('تایید سرپرست', 'تایید سرپرست'), ('تایید ناظر', 'تایید ناظر'), ('تایید نشده', 'تایید نشده')], default='در دست بررسی', max_length=30, verbose_name='وضیعت'),
        ),
    ]
