# Generated by Django 3.2.6 on 2021-09-15 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest', '0004_restmodel_timeavg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restmodel',
            name='timeavg',
        ),
        migrations.AddField(
            model_name='restmodel',
            name='user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری'),
        ),
    ]
