# Generated by Django 3.2.6 on 2021-09-22 22:04

from django.db import migrations
import django_jalali.db.models
import jdatetime


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_auto_20210920_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='restmodel',
            name='date',
            field=django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AddField(
            model_name='restmodel',
            name='dateexit',
            field=django_jalali.db.models.jDateField(null=True, verbose_name='مدت مرخصی'),
        ),
        migrations.AlterField(
            model_name='repmodel',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now, null=True, verbose_name='تاریخ ثبت'),
        ),
    ]
