# Generated by Django 3.2.6 on 2021-08-12 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('report', models.TextField(verbose_name='گزارش')),
                ('date', models.DateTimeField(verbose_name='تاریخ ثبت')),
                ('shift', models.CharField(choices=[('شیفت A', 'شیفت A'), ('شیفت B', 'شیفت B'), ('شیفت C', 'شیفت C')], max_length=50, verbose_name='شیفت')),
                ('acepet', models.CharField(choices=[('تایید نشده', 'تایید نشده'), ('تایید سر شیفت', 'تایید سر شیفت'), ('تایید نهایی', 'تایید نهایی')], default='تایید نشده', max_length=30)),
                ('slug', models.SlugField(max_length=200, unique_for_date='date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش',
            },
        ),
    ]
