# Generated by Django 3.2.6 on 2021-08-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='shift',
            field=models.CharField(choices=[('شیفت A', 'شیفت A'), ('شیفت B', 'شیفت B'), ('شیفت C', 'شیفت C')], max_length=50, null=True, verbose_name='شیفت'),
        ),
    ]
