# Generated by Django 3.2.6 on 2021-09-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_reportmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='date',
            field=models.DateTimeField(verbose_name='تاریخ ثبت'),
        ),
    ]
