# Generated by Django 3.2.6 on 2021-09-21 22:42

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_reportmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2021, 9, 22), verbose_name='تاریخ ثبت'),
        ),
    ]
