# Generated by Django 3.2.6 on 2021-09-21 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_alter_reportmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 2, 14, 23, 556144), verbose_name='تاریخ ثبت'),
        ),
    ]
