# Generated by Django 3.2.6 on 2021-09-21 23:19

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_alter_reportmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default='2021-09-22 02:49', verbose_name='تاریخ ثبت'),
        ),
    ]
