# Generated by Django 3.2.6 on 2021-09-22 22:04

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_alter_reportmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 9, 23, 1, 34, 5, 858166), verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='slug',
            field=models.SlugField(max_length=200, unique_for_date='date', verbose_name='آدرس گزارش'),
        ),
    ]
