# Generated by Django 3.2.6 on 2021-09-22 22:19

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_auto_20210923_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 9, 23, 1, 49, 6, 133860), verbose_name='تاریخ ثبت'),
        ),
    ]
