# Generated by Django 3.2.6 on 2021-09-25 08:55

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_alter_reportmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 9, 25, 8, 55, 7, 90778), verbose_name='تاریخ ثبت'),
        ),
    ]
