# Generated by Django 3.2.6 on 2021-08-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
